version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_USER=api
      - DB_NAME=api
      - DB_PASS=api
      - DB_HOST=postgres  # PostgreSQLサービスの名前と一致させる
      - DB_PORT=5432
    depends_on:
      - postgres  # PostgreSQLサービスの名前と一致させる
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api
      - POSTGRES_DB=api
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
